**Q1:** Implement the Simple Linear Regression for the data given below and predict the house price for 
a house with plot size 3000, 2000 and 1500 feet:

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


In [2]:
df=pd.read_csv("housePrice.csv")

In [3]:
print(df)

   House Price in $1000s (X)  Square feet (Y)
0                        245             1400
1                        312             1600
2                        279             1700
3                        308             1875
4                        199             1100
5                        219             1550
6                        405             2350
7                        324             2450
8                        319             1425
9                        255             1700


In [4]:
X = df.iloc[:, :-1].values
print(X)

[[245]
 [312]
 [279]
 [308]
 [199]
 [219]
 [405]
 [324]
 [319]
 [255]]


In [5]:
Y = df.iloc[:, -1].values
print(Y)

[1400 1600 1700 1875 1100 1550 2350 2450 1425 1700]


In [6]:
reg = LinearRegression()

In [7]:
reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
print('Coefficients: ', reg.coef_)

Coefficients:  [5.29132989]


In [9]:
print(reg.predict([[3000]]))

[16073.02364994]


In [10]:
print(reg.predict([[2000]]))

[10781.69376237]


In [11]:
print(reg.predict([[1500]]))

[8136.02881858]


## Stock Price Prediction

**Q2: Implement the Multiple Linear Regression for the data given below**

predict the stock index price if interest rate is 1.5 and unemployment rate is 5.8

In [12]:
df2 = pd.read_csv("stockPrice.csv")

In [13]:
print(df2)

    Year  Month  Interest_Rate  Unemployment_Rate  Stock_Index_Price
0   2017     12           2.75                5.3               1464
1   2017     11           2.50                5.3               1394
2   2017     10           2.50                5.3               1357
3   2017      9           2.50                5.3               1293
4   2017      8           2.50                5.4               1256
5   2017      7           2.50                5.6               1254
6   2017      6           2.50                5.5               1234
7   2017      5           2.25                5.5               1195
8   2017      4           2.25                5.5               1159
9   2017      3           2.25                5.6               1167
10  2017      2           2.00                5.7               1130
11  2017      1           2.00                5.9               1075
12  2016     12           2.00                6.0               1047
13  2016     11           1.75    

In [14]:
X2 = df2.iloc[:, :-1].values
print(X2)

[[2.017e+03 1.200e+01 2.750e+00 5.300e+00]
 [2.017e+03 1.100e+01 2.500e+00 5.300e+00]
 [2.017e+03 1.000e+01 2.500e+00 5.300e+00]
 [2.017e+03 9.000e+00 2.500e+00 5.300e+00]
 [2.017e+03 8.000e+00 2.500e+00 5.400e+00]
 [2.017e+03 7.000e+00 2.500e+00 5.600e+00]
 [2.017e+03 6.000e+00 2.500e+00 5.500e+00]
 [2.017e+03 5.000e+00 2.250e+00 5.500e+00]
 [2.017e+03 4.000e+00 2.250e+00 5.500e+00]
 [2.017e+03 3.000e+00 2.250e+00 5.600e+00]
 [2.017e+03 2.000e+00 2.000e+00 5.700e+00]
 [2.017e+03 1.000e+00 2.000e+00 5.900e+00]
 [2.016e+03 1.200e+01 2.000e+00 6.000e+00]
 [2.016e+03 1.100e+01 1.750e+00 5.900e+00]
 [2.016e+03 1.000e+01 1.750e+00 5.800e+00]
 [2.016e+03 9.000e+00 1.750e+00 6.100e+00]
 [2.016e+03 8.000e+00 1.750e+00 6.200e+00]
 [2.016e+03 7.000e+00 1.750e+00 6.100e+00]
 [2.016e+03 6.000e+00 1.750e+00 6.100e+00]
 [2.016e+03 5.000e+00 1.750e+00 6.100e+00]
 [2.016e+03 4.000e+00 1.750e+00 5.900e+00]
 [2.016e+03 3.000e+00 1.750e+00 6.200e+00]
 [2.016e+03 2.000e+00 1.750e+00 6.200e+00]
 [2.016e+03

In [15]:
Y2 = df2.iloc[:, -1].values
print(Y2)

[1464 1394 1357 1293 1256 1254 1234 1195 1159 1167 1130 1075 1047  965
  943  958  971  949  884  866  876  822  704  719]


In [16]:
reg2 = LinearRegression()

In [17]:
reg2.fit(X2,Y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
print(reg2.predict([[2021,9,1.5,5.8]]))

[2621.77182291]
