**Q1: Gaussian Naïve Bayes Classifier**

Implement Gaussian Naïve Bayes Classifier on the Iris dataset/ 
or any other relevant dataset from sklearn.datasets using inbuilt function.


In [1]:
import pandas as pd
import numpy as np 
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
iris = datasets.load_iris()

In [3]:
df1 = pd.DataFrame(iris.data, columns=iris.feature_names) 
df2 = pd.DataFrame(iris.target)
df = pd.concat([df1,df2],axis=1)

In [4]:
dfx = df.iloc[:,:4]
X_train, X_test, Y_train, Y_test = train_test_split(dfx, df2, test_size=0.3, random_state=8)

In [5]:
scaler = StandardScaler()
dfx_train = scaler.fit_transform(X_train)
dfx_test = scaler.fit_transform(X_test)

In [6]:
nb = GaussianNB()
nb.fit(dfx_train,Y_train)
predicted = nb.predict(dfx_test)
predicted

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 2, 1, 0, 0, 2, 2, 1, 2, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 0,
       1, 1, 1, 0, 2, 0, 0, 2, 0, 0, 0, 2, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1,
       2])

**Q2. Performance Evaluation of the Classifier:**

Evaluate the performance of the classifier using metrics library 
based on the parameters like confusion matrix, accuracy, 
precision, recall, F-1 Score, TPR, TNR, FPR and FNR.

In [7]:
accuracy = accuracy_score(Y_test, predicted, normalize = True)
print(accuracy)
report = classification_report(Y_test, predicted)
print(report)
matrix = confusion_matrix(Y_test, predicted)
print(matrix)

0.8666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.86      0.75      0.80        16
           2       0.75      0.86      0.80        14

    accuracy                           0.87        45
   macro avg       0.87      0.87      0.87        45
weighted avg       0.87      0.87      0.87        45

[[15  0  0]
 [ 0 12  4]
 [ 0  2 12]]


In [8]:
FP = matrix.sum(axis=0) - np.diag(matrix) 
FN = matrix.sum(axis=1) - np.diag(matrix)
TP = np.diag(matrix)
TN = matrix.sum() - (FP + FN + TP)
FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)

print(TP,TN,FP,FN)
TPR = TP/(TP+FN)
TNR = TN/(TN+FP)
FPR = FP/(FP+TN)
FNR = FN/(FN+TP)
print(TPR,TNR,FPR,FNR)

[15. 12. 12.] [30. 27. 27.] [0. 2. 4.] [0. 4. 2.]
[1.         0.75       0.85714286] [1.         0.93103448 0.87096774] [0.         0.06896552 0.12903226] [0.         0.25       0.14285714]
